### ISSUE TITLE
some feedback of demo

### ISSUE THREAD

**Issue by ssmem** [MegviiRobot/MegBA#1]
Hello, I tried your demo of BAL_Double.
I have 2 questions of it.
1. The program will take 100% of my cpu even I have no data (Venice). There is no strategy of data checking.
2. The program will take 100% of my cpu when I input params world_size==2. But I have only 1 gpu. The program stay at that progress and use my cpu. When I input right gpu number of 1, the program solved problem very fast.
Finally, I suggest the program should more robust of the main progress. For example, some checking and logs let us know what happened. And I also want to know why it take all of my cpu when nothing to solve.
Many thanks for watching that! Your work is pretty well that compared with ceres. I think there are still some small problem to solve on the level of program.

**Comment by JieRen98** [comment]
Thank you for your interest in MegBA.

The cpu 100% occputation is due to https://github.com/MegviiRobot/MegBA/blob/main/src/resource/Manager.cpp#L19. It blocks the main thread until all devices return.

We will continue to make MegBA more robust, e.g., adding more exception throws and log messages to help the user with easier debugging.
